.aws/dev_task_definition.json, .aws/staging_task_definition.json
Removed unnecessary lines from AWS task definitions
=> Fix AWS task definitions

.aws/dev_task_definition.json, .aws/staging_task_definition.json, .github/workflows/pull_request_ci.yml, .github/workflows/staging_ci.yml, README.md, backend/Dockerfile
Add support for AWS container health checks
=> [FEAT] Container health checks

.github/workflows/pull_request_ci.yml, .github/workflows/staging_ci.yml
=> Add GitGuardian

frontend/.env.development, frontend/src/App.test.tsx, frontend/src/App.tsx
Added a simple test button to test the frontend's connection with the backend.
=> [FEAT] Add simple test status check

.aws/dev_task_definition.json, .aws/staging_task_definition.json
Add support for a database to backend
=> [FEAT] Add support for database

.github/workflows/pull_request_ci.yml, .github/workflows/staging_ci.yml, .husky/pre-commit, package-lock.json, package.json
- Added separation between backend and frontend
- Added eslint
=> Add features to the CI

backend/package-lock.json, frontend/package-lock.json, frontend/package.json, frontend/src/App.test.tsx, frontend/src/components/App.scss, frontend/src/components/App.tsx, frontend/src/components/Header.tsx, frontend/src/components/PollCreationPage.scss, frontend/src/components/PollCreationPage.tsx, frontend/src/components/QuestionComponent.scss, frontend/src/components/QuestionComponent.tsx, frontend/src/index.scss, frontend/src/index.tsx, frontend/src/styles/_colors.scss
Implementation for poll question creation 
Added common _color.scss file
Components for poll question creation -  pollcreationcomponent and questioncomponent
=> Frontend us 35

.github/workflows/pull_request_ci.yml, .github/workflows/staging_ci.yml, backend/README.md, frontend/package.json
Fix issue caused by yesterdays CI update
=> Fix issues caused by new CI config

.aws/dev_task_definition.json, .aws/staging_task_definition.json, .github/workflows/pull_request_ci.yml, .github/workflows/staging_ci.yml, README.md, backend/src/controllers/healthController.ts
Add DB connection strings for DEV and STAGING databases from AWS secrets into task definitions
=> Add DB connection strings as AWS secrets

.github/workflows/pull_request_ci.yml, .github/workflows/staging_ci.yml, backend/src/controllers/pollController.ts, backend/src/routes/v1/health.ts, backend/src/routes/v1/poll.ts
Make the endpoints better match RESTful API best practices.
Also added one dummy endpoint for future reference.
=> Make API endpoints better match REST API best practices

frontend/src/components/PollCreationPage.scss, frontend/src/components/PollCreationPage.tsx, frontend/src/styles/_colors.scss
Describe here
-   [X] I have performed a self-review of my code
=> 66 question removal

backend/src/controllers/pollController.ts, backend/src/models/IPolling.ts, backend/src/routes/v1/poll.test.ts, backend/src/services/VotingService.test.ts, backend/src/services/VotingService.ts, frontend/src/components/PollCreationPage.scss, frontend/src/components/PollCreationPage.tsx, frontend/src/components/QuestionComponent.scss, frontend/src/components/QuestionComponent.tsx, frontend/src/components/__tests__/QuestionComponent.test.tsx, frontend/src/styles/_colors.scss
Issue 35 and 75 implemented:
Style fixes added - textfields, dropdown
question removal implemented
vote count toggle, question cards
=> Style fix pollcreation

backend/src/controllers/pollController.ts, backend/src/routes/v1/poll.ts, backend/src/routes/v1/swagger_api_v1.json, backend/src/services/VotingService.test.ts, backend/src/services/VotingService.ts, backend/src/utils/badRequestError.ts, backend/src/utils/responses.ts
- Add `400 Bad Request` responses when user error
- Add `201 Created` response when POST request
- Add the correct absolute location header to poll creation
- Add location header to all answers on answering => Incorrect but there is no endpoint to get one answer
- Add missing documentation from Swagger
=> Correct response codes to backend requests

.github/workflows/pull_request_ci.yml, .github/workflows/staging_ci.yml
Added Swagger/OpenAPI validation to the backend and removed deployment to the development environment
=> Modify GitHub Actions

frontend/src/components/BasicSnackbar.tsx, frontend/src/components/MainView.tsx, frontend/src/components/PollCreationPage.tsx, frontend/src/services/pollService.ts
forward ref, and EmptyCheck fn dependency fixed
Main.tsx dummy content added
Describe here
=> build warnings resolved

frontend/src/App.test.tsx, frontend/src/components/App.tsx, frontend/src/components/PollAnsweringPage.scss
Fixed styling in poll answering page.
=> UI Improvements to poll answering page

.github/workflows/production_ci.yml, .github/workflows/pull_request_ci.yml, .github/workflows/staging_ci.yml, frontend/src/components/App.tsx
- Add concurrency to CI => Should be faster now
- Comment out unused imports that prevented frontend build
=> Add concurrency to CI

backend/src/models/MultiQuestion.test.ts, backend/src/models/MultiQuestion.ts, backend/src/models/MultiQuestionCollection.ts, backend/src/routes/v1/poll.test.ts
Fix for issue of poll results not returning question type-specific info for sub-questions of multi-questions.
Describe here
=> make MultiQuestion use factory

.github/workflows/production_ci.yml, .github/workflows/staging_ci.yml, backend/src/app.ts, frontend/src/components/App.tsx, frontend/src/services/pollService.ts, frontend/src/utils/getBackendUrl.ts, infra/backend/ecs.tf, infra/backend/variables.tf, infra/frontend/cloudfront.tf, infra/frontend/variables.tf
Change URL to use backend load balancer URL instead of "/api" path.
=> Change the API URL that the frontend uses

.github/workflows/end_to_end_tests.yml, README.md, frontend/cypress.config.ts, frontend/cypress/e2e/1-getting-started/todo.cy.js, frontend/cypress/fixtures/example.json, frontend/cypress/support/commands.ts, frontend/cypress/support/e2e.ts, frontend/package-lock.json, frontend/package.json
=> Init Cypress

frontend/src/components/PollCreation.scss
Toggle track is pink when checked.
=> Change checked toggle color

backend/package-lock.json, frontend/src/components/Header.tsx, frontend/src/components/Login.tsx, frontend/src/components/NavBar.tsx, frontend/src/components/Registration.tsx, frontend/src/services/loginAndRegisterService.tsx
- User login & registration (@Marakke)
- Logout (@Jontzii)
=> Login and register integration with backend

frontend/src/components/Login.tsx, frontend/src/services/pollAndUserService.ts
=> Login fixes branch

frontend/src/services/pollAndUserService.ts, frontend/src/utils/getAuthorizationToken.ts
=> bearer string removed

.github/workflows/end_to_end_tests.yml
=> Disable some E2E tests

frontend/src/components/AdminView.tsx, frontend/src/components/AdminViewPoll.tsx, frontend/src/components/AdminViewUser.tsx, frontend/src/components/AdminViewUserProfile.tsx, frontend/src/components/PollCreation.tsx, frontend/src/components/PollEditView.tsx, frontend/src/components/PollResult.tsx, frontend/src/services/pollService.ts, frontend/src/services/userService.ts
- Seperated pollAndUserService to pollService and userService
- Created fetchPoll api call
=> 160 separate pollanduserservice and create fetchpoll

frontend/src/components/AdminView.tsx, frontend/src/components/AdminViewPoll.tsx, frontend/src/components/AdminViewUser.tsx, frontend/src/components/AdminViewUserProfile.tsx, frontend/src/components/App.tsx, frontend/src/components/Login.tsx, frontend/src/components/PollCreation.tsx, frontend/src/components/PollEditView.tsx, frontend/src/components/PollResult.tsx, frontend/src/components/Question.tsx, frontend/src/components/ResultCard.tsx, frontend/src/components/ResultOption.tsx
- Remove most of the console logs
- Make `PollEditView` use `useParams`
=> Small fixes

.github/workflows/production_ci.yml, .github/workflows/staging_ci.yml
Remove duplicate environments from CI pipelines
=> [FIX] Environments from CI

backend/package-lock.json, backend/prisma/migrations/20221207224129_made_poll_creator_optional/migration.sql, backend/prisma/schema.prisma, backend/src/controllers/pollController.ts, backend/src/models/IPoll.ts, backend/src/models/IPolling.ts, backend/src/models/Poll.test.ts, backend/src/models/Poll.ts, backend/src/routes/v1/poll.test.ts, backend/src/routes/v1/poll/public.ts, backend/src/routes/v1/swagger_api_v1.json, backend/src/routes/v1/user.test.ts
Made poll creation possible without being logged in. Finished swagger documentation. I used ChatGPT to generate documentation for new endpoints (fixing its output manually when needed), so if there is some unusual silly mistake somewhere, it might be because of that. I also updated and ran the integration tests (poll.test.ts & user.test.ts) to make sure everything works (at least according to those tests).
=> make poll creator optional & finish documentation

README.md, backend/src/routes/v1/swagger_api_v1.json
=> Add correct URLs to Swagger

.github/workflows/production_ci.yml, .github/workflows/staging_ci.yml, backend/Dockerfile, infra/backend/ecs.tf
- Add curl as part of the slim deployment image
- Remove unnecessary port opening
- Update migration to happen after deployment
=> Fix deployment issues

backend/src/models/BooleanQuestion.ts, backend/src/models/Poll.ts, backend/src/routes/v1/poll.test.ts
Fixed bug on backend where answering boolean questions directly under the poll as false was not possible.
=> fix boolean question answering bug on backend

backend/package-lock.json, frontend/src/components/PollCreation.tsx, frontend/src/components/Registration.tsx, frontend/src/components/__tests__/PollCreation.test.tsx
Describe here
-   [X] I have performed a self-review of my code
=> Manual systeem testing

frontend/src/components/__tests__/PollCreation.test.tsx, frontend/src/components/__tests__/Question.test.tsx
existing test cases uncommented
Describe here
=> testcases uncommented
